mock/onlinexam/urls.py
from django.urls import path, include
from django.contrib import admin
from exam import views
from django.contrib.auth.views import LogoutView, LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),


    path('', views.home_view, name=''),
    path('logout', LogoutView.as_view(
        template_name='exam/logout.html'), name='logout'),
    path('contactus', views.contactus_view),
    path('afterlogin', views.afterlogin_view, name='afterlogin'),



    path('adminclick', views.adminclick_view),
    path('adminlogin', LoginView.as_view(
        template_name='exam/adminlogin.html'), name='adminlogin'),
    path('admin-dashboard', views.admin_dashboard_view, name='admin-dashboard'),
    path('admin-teacher', views.admin_teacher_view, name='admin-teacher'),
    path('admin-view-teacher', views.admin_view_teacher_view,
         name='admin-view-teacher'),
    path('update-teacher/<int:pk>',
         views.update_teacher_view, name='update-teacher'),
    path('delete-teacher/<int:pk>',
         views.delete_teacher_view, name='delete-teacher'),
    path('admin-view-pending-teacher', views.admin_view_pending_teacher_view,
         name='admin-view-pending-teacher'),
    path('admin-view-teacher-salary', views.admin_view_teacher_salary_view,
         name='admin-view-teacher-salary'),
    path('approve-teacher/<int:pk>',
         views.approve_teacher_view, name='approve-teacher'),
    path('reject-teacher/<int:pk>',
         views.reject_teacher_view, name='reject-teacher'),

    path('admin-student', views.admin_student_view, name='admin-student'),
    path('admin-view-student', views.admin_view_student_view,
         name='admin-view-student'),
    path('admin-view-student-marks', views.admin_view_student_marks_view,
         name='admin-view-student-marks'),
    path('admin-view-marks/<int:pk>',
         views.admin_view_marks_view, name='admin-view-marks'),
    path('admin-check-marks/<int:pk>',
         views.admin_check_marks_view, name='admin-check-marks'),
    path('update-student/<int:pk>',
         views.update_student_view, name='update-student'),
    path('delete-student/<int:pk>',
         views.delete_student_view, name='delete-student'),

    path('admin-course', views.admin_course_view, name='admin-course'),
    path('admin-add-course', views.admin_add_course_view, name='admin-add-course'),
    path('admin-view-course', views.admin_view_course_view,
         name='admin-view-course'),
    path('delete-course/<int:pk>', views.delete_course_view, name='delete-course'),

    path('admin-question', views.admin_question_view, name='admin-question'),
    path('admin-add-question', views.admin_add_question_view,
         name='admin-add-question'),
    path('admin-view-question', views.admin_view_question_view,
         name='admin-view-question'),
    path('view-question/<int:pk>', views.view_question_view, name='view-question'),
    path('delete-question/<int:pk>',
         views.delete_question_view, name='delete-question'),
]

mock/student/urls.py
from django.urls import path
from student import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('studentclick', views.studentclick_view),
    path('studentlogin', LoginView.as_view(
        template_name='student/studentlogin.html'), name='studentlogin'),
    path('studentsignup', views.student_signup_view, name='studentsignup'),
    path('student-dashboard', views.student_dashboard_view,
         name='student-dashboard'),
    path('student-exam', views.student_exam_view, name='student-exam'),
    path('take-exam/<int:pk>', views.take_exam_view, name='take-exam'),
    path('start-exam/<int:pk>', views.start_exam_view, name='start-exam'),

    path('calculate-marks', views.calculate_marks_view, name='calculate-marks'),
    path('view-result', views.view_result_view, name='view-result'),
    path('check-marks/<int:pk>', views.check_marks_view, name='check-marks'),
    path('student-marks', views.student_marks_view, name='student-marks'),
]

mock/teacher/urls.py
from django.urls import path
from teacher import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('teacherclick', views.teacherclick_view),
    path('teacherlogin', LoginView.as_view(
        template_name='teacher/teacherlogin.html'), name='teacherlogin'),
    path('teachersignup', views.teacher_signup_view, name='teachersignup'),
    path('teacher-dashboard', views.teacher_dashboard_view,
         name='teacher-dashboard'),
    path('teacher-exam', views.teacher_exam_view, name='teacher-exam'),
    path('teacher-add-exam', views.teacher_add_exam_view, name='teacher-add-exam'),
    path('teacher-view-exam', views.teacher_view_exam_view,
         name='teacher-view-exam'),
    path('delete-exam/<int:pk>', views.delete_exam_view, name='delete-exam'),


    path('teacher-question', views.teacher_question_view, name='teacher-question'),
    path('teacher-add-question', views.teacher_add_question_view,
         name='teacher-add-question'),
    path('teacher-view-question', views.teacher_view_question_view,
         name='teacher-view-question'),
    path('see-question/<int:pk>', views.see_question_view, name='see-question'),
    path('remove-question/<int:pk>',
         views.remove_question_view, name='remove-question'),
]

mock/teacher/models.py
from django.db import models
from django.contrib.auth.models import User

class Teacher(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic= models.ImageField(upload_to='profile_pic/Teacher/',null=True,blank=True)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=False)
    status= models.BooleanField(default=False)
    salary=models.PositiveIntegerField(null=True)

    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    
    @property
    def get_instance(self):
        return self
    
    def __str__(self):
        return self.user.first_name

mock/teacher/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class TeacherUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','password']
        widgets = {
        'password': forms.PasswordInput()
        }

class TeacherForm(forms.ModelForm):
    class Meta:
        model=models.Teacher
        fields=['address','mobile','profile_pic']

mock/teacher/views.py
from django.shortcuts import render, redirect, reverse
from . import forms, models
from django.db.models import Sum
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.conf import settings
from datetime import date, timedelta
from exam import models as QMODEL
from student import models as SMODEL
from exam import forms as QFORM


# for showing signup/login button for teacher
def teacherclick_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('afterlogin')
    return render(request, 'teacher/teacherclick.html')


def teacher_signup_view(request):
    userForm = forms.TeacherUserForm()
    teacherForm = forms.TeacherForm()
    mydict = {'userForm': userForm, 'teacherForm': teacherForm}
    if request.method == 'POST':
        userForm = forms.TeacherUserForm(request.POST)
        teacherForm = forms.TeacherForm(request.POST, request.FILES)
        if userForm.is_valid() and teacherForm.is_valid():
            user = userForm.save()
            user.set_password(user.password)
            user.save()
            teacher = teacherForm.save(commit=False)
            teacher.user = user
            teacher.save()
            my_teacher_group = Group.objects.get_or_create(name='TEACHER')
            my_teacher_group[0].user_set.add(user)
        return HttpResponseRedirect('teacherlogin')
    return render(request, 'teacher/teachersignup.html', context=mydict)


def is_teacher(user):
    return user.groups.filter(name='TEACHER').exists()


@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_dashboard_view(request):
    dict = {

        'total_course': QMODEL.Course.objects.all().count(),
        'total_question': QMODEL.Question.objects.all().count(),
        'total_student': SMODEL.Student.objects.all().count()
    }
    return render(request, 'teacher/teacher_dashboard.html', context=dict)


@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_exam_view(request):
    return render(request, 'teacher/teacher_exam.html')


@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_add_exam_view(request):
    courseForm = QFORM.CourseForm()
    if request.method == 'POST':
        courseForm = QFORM.CourseForm(request.POST)
        if courseForm.is_valid():
            courseForm.save()
        else:
            print("form is invalid")
        return HttpResponseRedirect('/teacher/teacher-view-exam')
    return render(request, 'teacher/teacher_add_exam.html', {'courseForm': courseForm})


@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_view_exam_view(request):
    courses = QMODEL.Course.objects.all()
    return render(request, 'teacher/teacher_view_exam.html', {'courses': courses})


@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def delete_exam_view(request, pk):
    course = QMODEL.Course.objects.get(id=pk)
    course.delete()
    return HttpResponseRedirect('/teacher/teacher-view-exam')


@login_required(login_url='adminlogin')
def teacher_question_view(request):
    return render(request, 'teacher/teacher_question.html')


@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_add_question_view(request):
    questionForm = QFORM.QuestionForm()
    if request.method == 'POST':
        questionForm = QFORM.QuestionForm(request.POST)
        if questionForm.is_valid():
            question = questionForm.save(commit=False)
            course = QMODEL.Course.objects.get(id=request.POST.get('courseID'))
            question.course = course
            question.save()
        else:
            print("form is invalid")
        return HttpResponseRedirect('/teacher/teacher-view-question')
    return render(request, 'teacher/teacher_add_question.html', {'questionForm': questionForm})


@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def teacher_view_question_view(request):
    courses = QMODEL.Course.objects.all()
    return render(request, 'teacher/teacher_view_question.html', {'courses': courses})


@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def see_question_view(request, pk):
    questions = QMODEL.Question.objects.all().filter(course_id=pk)
    return render(request, 'teacher/see_question.html', {'questions': questions})


@login_required(login_url='teacherlogin')
@user_passes_test(is_teacher)
def remove_question_view(request, pk):
    question = QMODEL.Question.objects.get(id=pk)
    question.delete()
    return HttpResponseRedirect('/teacher/teacher-view-question')

mock/templates/teacher/see_question.html
{% extends "base/dashboard.html" %} 
{% load static %}

{% block sidebar %} 
{% include "base/components/teacher-sidebar.html" %}
{% endblock %} 

{% block main %}
<div class="dashboard-exams">
  <h3>Mes résultats</h3>
  <div class="dashboard-exams-table">
    <div class="dashboard-exams-table-header">
      <div>Questions</div>
      <div>Note</div>
      <div>Actions</div>
    </div>
    <div class="dashboard-exams-table-body">
      {% for c in questions %}
      <div class="dashboard-exams-table-row">
        <div>{{c.question}}</div>
        <div>{{c.marks}}</div>
        <div>
          <a class="dashboard-exams-table-row-action" href="{% url 'remove-question' c.id  %}">
            <i class="fas fa-trash"></i>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock main %}

mock/templates/teacher/teacher_add_exam.html
{% extends "base/dashboard.html" %} 
{% load widget_tweaks %} 
{% load static %}

{% block sidebar %}
  {% include "base/components/teacher-sidebar.html" %} 
{% endblock %} 

{% block main %}
<div class="dashboard-form">
  <h3 style="margin-bottom: 2.5rem">Ajouter un examen</h3>
  <form method="POST" autocomplete="off">
    {%csrf_token%}
    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      {% render_field courseForm.course_name placeholder="" %}
      <label for="course_name" class="input-label">Examen</label>
    </div>

    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      {% render_field courseForm.question_number placeholder="" %}
      <label for="question_number" class="input-label">Nombre de quesitons</label>
    </div>

    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      {% render_field courseForm.total_marks placeholder="" %}
      <label for="total_marks" class="input-label">Note total</label>
    </div>
    <button type="submit" class="btn btn-main">Ajouter Examen</button>
  </form>
</div>
{% endblock %}

mock/templates/teacher/teacher_add_question.html
{% extends "base/dashboard.html" %}
{% load widget_tweaks %}
{% load static %}

{% block sidebar %} 
  {% include "base/components/teacher-sidebar.html" %} 
{% endblock %} 

{% block main %}
<div class="dashboard-form">
  <h3 style="margin-bottom: 2.5rem">Ajouter un examen</h3>
  <form method="POST" autocomplete="off">
    {%csrf_token%}
    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      <label for="question" class="input-select-label">Examens</label>
      {% render_field questionForm.courseID|attr:'required:true' %}
    </div>

    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      <label for="question" class="input-select-label">Question</label>
      {% render_field questionForm.question|attr:'required:true' placeholder="Example: Laquelle des options suivantes n est pas une phase du modèle de prototypage?" %}
    </div>

    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      {% render_field questionForm.marks|attr:'required:true' placeholder="" %}
      <label for="question_number" class="input-label">Note</label>
    </div>

    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      {% render_field questionForm.option1|attr:'required:true' placeholder="" %}
      <label for="option1" class="input-label">Option 1</label>
    </div>

    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      {% render_field questionForm.option2|attr:'required:true' placeholder="" %}
      <label for="option2" class="input-label">Option 2</label>
    </div>

    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      {% render_field questionForm.option3|attr:'required:true' placeholder="" %}
      <label for="option3" class="input-label">Option 3</label>
    </div>
    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      {% render_field questionForm.option4|attr:'required:true' placeholder="" %}
      <label for="option4" class="input-label">Option 4</label>
    </div>
    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      <label for="answer" class="input-select-label">Réponse correcte</label>
      {% render_field questionForm.answer|attr:'required:true' %}
    </div>

    <button type="submit" class="btn btn-main">Ajouter Question</button>
  </form>
</div>
{% endblock %}

mock/templates/teacher/teacher_dashboard.html
{% extends "base/dashboard.html" %}
{% load widget_tweaks %}

{% block sidebar %}
  {% include "base/components/teacher-sidebar.html" %}
{% endblock %}

{% block main %}
    <div class="dashboard-link-grid">
      <div class="dashboard-link-card blue">
        <div>
          <h3>Étudiants inscrits</h3>
          <p>{{total_student}}</p>
        </div>
        <i class="fas fa-user-graduate f-left"></i>
      </div>
      <div class="dashboard-link-card purple">
        <div>
          <h3>Examens disponibles</h3>
          <p>{{total_course}}</p>
        </div> 
        <i class="fas fa-book f-left"></i>
      </div>
      <div class="dashboard-link-card red">
        <div>
          <h3>Nombre total de questions</h3>
          <p>{{total_question}}</p>
        </div>
        <i class="fas fa-question-circle f-left"></i>
      </div>
    <div>
{% endblock main %}

mock/templates/teacher/teacher_exam.html
{% extends "base/dashboard.html" %}
{% load widget_tweaks %}

{% block sidebar %}
  {% include "base/components/teacher-sidebar.html" %}
{% endblock %}

{% block main %}
    <div class="dashboard-link-grid">
      <a href="teacher-add-exam" class="dashboard-link-card blue">
        <div>
          <h3 style="margin: 0">Ajouter un examen</h3>
        </div>
        <i class="fas fa-plus f-left"></i>
      </a>
      <a href="teacher-view-exam" class="dashboard-link-card green">
        <div>
          <h3 style="margin: 0">Consulter les examens</h3>
        </div>
        <i class="fas fa-eye f-left"></i>
      </a>
    <div>
{% endblock main %}

mock/templates/teacher/teacher_question.html
{% extends "base/dashboard.html" %}
{% load widget_tweaks %}

{% block sidebar %}
  {% include "base/components/teacher-sidebar.html" %}
{% endblock %}

{% block main %}
    <div class="dashboard-link-grid">
      <a href="teacher-add-question" class="dashboard-link-card purple">
        <div>
          <h3 style="margin: 0">Ajouter une question</h3>
        </div>
        <i class="fas fa-plus f-left"></i>
      </a>
      <a href="teacher-view-question" class="dashboard-link-card red">
        <div>
          <h3 style="margin: 0">Consulter les questions</h3>
        </div>
        <i class="fas fa-eye f-left"></i>
      </a>
    <div>
{% endblock main %}

mock/templates/teacher/teacher_view_exam.html
{% extends "base/dashboard.html" %} 
{% load static %}

{% block sidebar %} 
{% include "base/components/teacher-sidebar.html" %}
{% endblock %} 

{% block main %}
<div class="dashboard-exams">
  <h3>Mes résultats</h3>
  <div class="dashboard-exams-table">
    <div class="dashboard-exams-table-header">
      <div>Examen</div>
      <div>Nombre de questions</div>
      <div>Nombre total de notes</div>
      <div>Actions</div>
    </div>
    <div class="dashboard-exams-table-body">
      {% for c in courses %}
      <div class="dashboard-exams-table-row">
        <div>{{c.course_name}}</div>
        <div>{{c.question_number}}</div>
        <div>{{c.total_marks}}</div>
        <div>
          <a class="dashboard-exams-table-row-action" href="{% url 'delete-exam' c.id  %}">
            <i class="fas fa-trash"></i>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock main %}

mock/templates/teacher/teacher_view_question.html
{% extends "base/dashboard.html" %} 
{% load static %}

{% block sidebar %} 
{% include "base/components/teacher-sidebar.html" %}
{% endblock %} 

{% block main %}
<div class="dashboard-exams">
  <h3>Mes résultats</h3>
  <div class="dashboard-exams-table">
    <div class="dashboard-exams-table-header">
      <div>Examen</div>
      <div>Nombre de questions</div>
      <div>Nombre total de notes</div>
      <div>Actions</div>
    </div>
    <div class="dashboard-exams-table-body">
      {% for c in courses %}
      <div class="dashboard-exams-table-row">
        <div>{{c.course_name}}</div>
        <div>{{c.question_number}}</div>
        <div>{{c.total_marks}}</div>
        <div>
          <a class="dashboard-exams-table-row-action" href="{% url 'see-question' c.id  %}">
            <i class="fas fa-eye"></i>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock main %}

mock/templates/teacher/teacher_wait_for_approval.html
{% extends "base/dashboard.html" %} 
{% load widget_tweaks %} 

{% block main %}
<div class="dashboard-waiting">
  <h1>Bonjour cher professeur {{request.user.first_name}},</h1>
  <p>
    <span>Votre compte n'a pas encore été ACTIVÉ!</span>
    <span
      >En attente d'approbation de l'administrateur. Vous pourrez bientôt
      accéder à votre compte après approbation.</span
    >
  </p>
</div>
{% endblock main %}

{% block footer %}
  {% include "base/components/footer.html" %}
{% endblock %}

mock/templates/teacher/teacherbase.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
 

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    body {
      margin: 0;
      padding: 0;
      font-family: "Gill Sans", sans-serif;;
    }

    header {
      position: fixed;
      background: #22242A;
      padding: 20px;
      width: 100%;
      z-index: 1;
    }

    .left_area h3 {
      color: #fff;
      margin: 0px;
      text-transform: uppercase;
      font-size: 22px;
      font-weight: 900;
    }

    .left_area span {
      color: #19B3D3;
    }

    .logout_btn {
      padding: 5px;
      background:#ef5350;
      text-decoration: none;
      float: right;
      margin-top: -30px;
      margin-right: 40px;
      border-radius: 2px;
      font-size: 15px;
      font-weight: 600;
      color: #fff;
      transition: 0.5s;

    }

    .logout_btn:hover {
      background: #bb403e;
    }

    .sidebar {
      background: #2f323a;
      margin-top: 70px;
      padding-top: 30px;
      position: fixed;
      left: 0;
      width: 250px;
      height: 100%;
      transition: 0.5s;
      transition-property: left;
    }

    .sidebar .profile_image {
      width: 100px;
      height: 100px;
      border-radius: 100px;
      margin-bottom: 10px;
    }

    .sidebar h4 {
      color: #ccc;
      margin-top: 0;
      
    }

    .sidebar a {
      color: #fff;
      display: block;
      width: 100%;
      line-height: 60px;
      text-decoration: none;
      padding-left: 40px;
      box-sizing: border-box;
      transition: 0.5s;

    }

    .sidebar a:hover {
      background:  #969696;
      color:white;
    }

    .sidebar i {
      padding-right: 10px;
    }

    label #sidebar_btn {
      z-index: 1;
      color: #fff;
      position: fixed;
      cursor: pointer;
      left: 300px;
      font-size: 20px;
      margin: 5px 0;
      transition: 0.5s;
      transition-property: color;
    }

    label #sidebar_btn:hover {
      color: #575757;
    }

    #check:checked~.sidebar {
      left: -190px;
    }

    #check:checked~.sidebar a span {
      display: none;
    }

    #check:checked~.sidebar a {
      font-size: 20px;
      margin-left: 170px;
      width: 80px;
    }

    .content {
      margin-left: 250px;
      background: url(background.png) no-repeat;
      background-position: center;
      background-size: cover;
      height: 100vh;
      transition: 0.5s;
    }

    #check:checked~.content {
      margin-left: 60px;
    }

    #check {
      display: none;
    }
  </style>


  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">


</head>

<body>

  <input type="checkbox" id="check">
  <!--header area start-->
  <header>
    <label for="check">
      <i style="left: 200px;margin-top: 17px;"class="fas fa-bars" id="sidebar_btn"></i>
    </label>
    <div class="left_area">
      <h3>Online Exam</h3>
    </div>
    <div class="right_area">
      <a href="/logout" class="logout_btn">Logout</a>
    </div>
  </header>
  <!--header area end-->
  <!--sidebar start-->
  <div class="sidebar">
    <center>

      <img src="{% static "image/teacher.png" %}" class="profile_image" alt="">
      <h4>{{request.user.first_name}}</h4>
      <h6 style="color: rgb(255, 255, 255);">( Teacher )</h6>

    </center>

    <a href="/teacher/teacher-dashboard"><i class="fas fa-tachometer-alt"></i><span>Dashboard</span></a>
    <a href="/teacher/teacher-exam"><i class="fas fa-book"></i><span>Manage Courses</span></a>
    <a href="/teacher/teacher-question"><i class="fas fa-question-circle"></i><span>Manage Questions</span></a>
  </div>
  <!--sidebar end-->


  <!--content start-->
  <div class="content">
    <br><br><br><br><br>
    {% block content %}

    {% endblock content %}


    <br><br><br>
    {% include "exam/footer.html" %}
  </div>
  <!--content end-->
</body>

</html>

mock/templates/teacher/teacherclick.html
{% extends "base/home.html" %} 
{% block title%}Teacher{% endblock %} 
{% load static %} 
{% block main %}
<div class="main-home-wrapper main-home-wrapper-teacher">
    <div class="main-home-wrapper-container">
        <h1>Bonjour Chers Enseignants</h1>
        <h3>et Bienvenue à Edumetric</h3>
        <div class="main-home-wrapper-container-buttons">
            <a class="btn btn-main" href="teachersignup" role="button">Inscription</a>
            <a class="btn btn-secondary" href="teacherlogin">Connexion</a>
        </div>
    </div>
</div>
{% endblock %}

mock/templates/teacher/teacherlogin.html
{% extends "base/authentication.html" %}
{% block title %}Connexion{% endblock%}
{% load widget_tweaks %}
{% load static %}
{% block main %}
<div class="auth-container">
  <form method="post" class="auth-form">
    {% csrf_token %}
    <h1>Accès enseignant</h1>
    <div class="input-wrapper">
        {% render_field form.username class="input-text" autocomplete="off" placeholder="" %}
        <label for="id_username" class="input-label">Utilisateur</label>
    </div>
    <div class="input-wrapper">
        {% render_field form.password class="input-text" autocomplete="off" placeholder="" %}
        <label for="id_password" class="input-label">Mot de passe</label>
    </div>

    <div class="auth-buttons">
      <button class="btn btn-main" type="submit">Connexion</button>
    </div>

  </form>
  <img src="{% static 'images/signin-image.jpg' %}" alt="" />
</div>
{% endblock %}

mock/templates/teacher/teachersignup.html
{% extends "base/authentication.html" %}
{% block title %}Connexion{% endblock%}
{% load widget_tweaks %}
{% load static %}
{% block main %}
<div class="auth-container">
  <img src="{% static 'images/signup-image.jpg' %}" alt="" />
  <form method="POST" autocomplete="off" enctype="multipart/form-data" class="auth-form">
    {% csrf_token %}
    <h1>Inscription des étudiants</h1>
    <div class="input-wrapper">
      {% render_field userForm.first_name|attr:'required:true' class="input-text" placeholder="" %}
      <label for="id_first_name" class="input-label">prénom</label>
    </div>
    <div class="input-wrapper">
      {% render_field userForm.last_name|attr:'required:true'  class="input-text" placeholder="" %}
      <label for="id_last_name" class="input-label">Nom</label>
    </div>

    <div class="input-wrapper">
      {% render_field teacherForm.mobile|attr:'required:true'  class="input-text" placeholder="" %}
      <label for="id_mobile" class="input-label">Numéro de contact</label>
    </div>
    <div class="input-wrapper">
      {% render_field teacherForm.address|attr:'required:true'  class="input-text" placeholder="" %}
      <label for="id_address" class="input-label">Adresse</label>
    </div>

    <div class="input-wrapper">
      {% render_field userForm.username|attr:'required:true'  class="input-text" placeholder="" %}
      <label for="id_username" class="input-label">Utilisateur</label>
    </div>
    <div class="input-wrapper">
      {% render_field userForm.password|attr:'required:true'  class="input-text" placeholder="" %}
      <label for="id_password" class="input-label">Password</label>
    </div>

    <div class="input-wrapper">
      <label for="id_profile_pic" class="input-select-label">Profile Picture</label>
      {% render_field teacherForm.profile_pic|attr:'required:true' class="input-text" placeholder="" %}
    </div>

    <div class="auth-buttons">
      <button class="btn btn-main" type="submit">Inscription</button>
    </div>  
  </form>
</div>
{% endblock %}