mock/onlinexam/urls.py
from django.urls import path, include
from django.contrib import admin
from exam import views
from django.contrib.auth.views import LogoutView, LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),


    path('', views.home_view, name=''),
    path('logout', LogoutView.as_view(
        template_name='exam/logout.html'), name='logout'),
    path('contactus', views.contactus_view),
    path('afterlogin', views.afterlogin_view, name='afterlogin'),



    path('adminclick', views.adminclick_view),
    path('adminlogin', LoginView.as_view(
        template_name='exam/adminlogin.html'), name='adminlogin'),
    path('admin-dashboard', views.admin_dashboard_view, name='admin-dashboard'),
    path('admin-teacher', views.admin_teacher_view, name='admin-teacher'),
    path('admin-view-teacher', views.admin_view_teacher_view,
         name='admin-view-teacher'),
    path('update-teacher/<int:pk>',
         views.update_teacher_view, name='update-teacher'),
    path('delete-teacher/<int:pk>',
         views.delete_teacher_view, name='delete-teacher'),
    path('admin-view-pending-teacher', views.admin_view_pending_teacher_view,
         name='admin-view-pending-teacher'),
    path('admin-view-teacher-salary', views.admin_view_teacher_salary_view,
         name='admin-view-teacher-salary'),
    path('approve-teacher/<int:pk>',
         views.approve_teacher_view, name='approve-teacher'),
    path('reject-teacher/<int:pk>',
         views.reject_teacher_view, name='reject-teacher'),

    path('admin-student', views.admin_student_view, name='admin-student'),
    path('admin-view-student', views.admin_view_student_view,
         name='admin-view-student'),
    path('admin-view-student-marks', views.admin_view_student_marks_view,
         name='admin-view-student-marks'),
    path('admin-view-marks/<int:pk>',
         views.admin_view_marks_view, name='admin-view-marks'),
    path('admin-check-marks/<int:pk>',
         views.admin_check_marks_view, name='admin-check-marks'),
    path('update-student/<int:pk>',
         views.update_student_view, name='update-student'),
    path('delete-student/<int:pk>',
         views.delete_student_view, name='delete-student'),

    path('admin-course', views.admin_course_view, name='admin-course'),
    path('admin-add-course', views.admin_add_course_view, name='admin-add-course'),
    path('admin-view-course', views.admin_view_course_view,
         name='admin-view-course'),
    path('delete-course/<int:pk>', views.delete_course_view, name='delete-course'),

    path('admin-question', views.admin_question_view, name='admin-question'),
    path('admin-add-question', views.admin_add_question_view,
         name='admin-add-question'),
    path('admin-view-question', views.admin_view_question_view,
         name='admin-view-question'),
    path('view-question/<int:pk>', views.view_question_view, name='view-question'),
    path('delete-question/<int:pk>',
         views.delete_question_view, name='delete-question'),
]

mock/student/urls.py
from django.urls import path
from student import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('studentclick', views.studentclick_view),
    path('studentlogin', LoginView.as_view(
        template_name='student/studentlogin.html'), name='studentlogin'),
    path('studentsignup', views.student_signup_view, name='studentsignup'),
    path('student-dashboard', views.student_dashboard_view,
         name='student-dashboard'),
    path('student-exam', views.student_exam_view, name='student-exam'),
    path('take-exam/<int:pk>', views.take_exam_view, name='take-exam'),
    path('start-exam/<int:pk>', views.start_exam_view, name='start-exam'),

    path('calculate-marks', views.calculate_marks_view, name='calculate-marks'),
    path('view-result', views.view_result_view, name='view-result'),
    path('check-marks/<int:pk>', views.check_marks_view, name='check-marks'),
    path('student-marks', views.student_marks_view, name='student-marks'),
]

mock/exam/models.py
from django.db import models
from student.models import Student

class Course(models.Model):
   course_name = models.CharField(max_length=50)
   question_number = models.PositiveIntegerField()
   total_marks = models.PositiveIntegerField()
   def __str__(self):
        return self.course_name

class Question(models.Model):
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    marks=models.PositiveIntegerField()
    question=models.CharField(max_length=600)
    option1=models.CharField(max_length=200)
    option2=models.CharField(max_length=200)
    option3=models.CharField(max_length=200)
    option4=models.CharField(max_length=200)
    cat=(('Option1','Option1'),('Option2','Option2'),('Option3','Option3'),('Option4','Option4'))
    answer=models.CharField(max_length=200,choices=cat)

class Result(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    exam = models.ForeignKey(Course,on_delete=models.CASCADE)
    marks = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now=True)

mock/exam/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class ContactusForm(forms.Form):
    Name = forms.CharField(max_length=30)
    Email = forms.EmailField()
    Message = forms.CharField(max_length=500,widget=forms.Textarea(attrs={'rows': 3, 'cols': 30}))

class TeacherSalaryForm(forms.Form):
    salary=forms.IntegerField()

class CourseForm(forms.ModelForm):
    class Meta:
        model=models.Course
        fields=['course_name','question_number','total_marks']

class QuestionForm(forms.ModelForm):
    
    #this will show dropdown __str__ method course model is shown on html so override it
    #to_field_name this will fetch corresponding value  user_id present in course model and return it
    courseID=forms.ModelChoiceField(queryset=models.Course.objects.all(),empty_label="Course Name", to_field_name="id")
    class Meta:
        model=models.Question
        fields=['marks','question','option1','option2','option3','option4','answer']
        widgets = {
            'question': forms.Textarea(attrs={'rows': 3, 'cols': 50})
        }

mock/exam/views.py
from django.shortcuts import render,redirect,reverse
from . import forms,models
from django.db.models import Sum
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required,user_passes_test
from django.conf import settings
from datetime import date, timedelta
from django.db.models import Q
from django.core.mail import send_mail
from teacher import models as TMODEL
from student import models as SMODEL
from teacher import forms as TFORM
from student import forms as SFORM
from django.contrib.auth.models import User



def home_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('afterlogin')  
    return render(request,'exam/index.html')


def is_teacher(user):
    return user.groups.filter(name='TEACHER').exists()

def is_student(user):
    return user.groups.filter(name='STUDENT').exists()

def afterlogin_view(request):
    if is_student(request.user):      
        return redirect('student/student-dashboard')
                
    elif is_teacher(request.user):
        accountapproval=TMODEL.Teacher.objects.all().filter(user_id=request.user.id,status=True)
        if accountapproval:
            return redirect('teacher/teacher-dashboard')
        else:
            return render(request,'teacher/teacher_wait_for_approval.html')
    else:
        return redirect('admin-dashboard')



def adminclick_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('afterlogin')
    return HttpResponseRedirect('adminlogin')


@login_required(login_url='adminlogin')
def admin_dashboard_view(request):
    dict={
    'total_student':SMODEL.Student.objects.all().count(),
    'total_teacher':TMODEL.Teacher.objects.all().filter(status=True).count(),
    'total_course':models.Course.objects.all().count(),
    'total_question':models.Question.objects.all().count(),
    }
    return render(request,'exam/admin_dashboard.html',context=dict)

@login_required(login_url='adminlogin')
def admin_teacher_view(request):
    dict={
    'total_teacher':TMODEL.Teacher.objects.all().filter(status=True).count(),
    'pending_teacher':TMODEL.Teacher.objects.all().filter(status=False).count(),
    'salary':TMODEL.Teacher.objects.all().filter(status=True).aggregate(Sum('salary'))['salary__sum'],
    }
    return render(request,'exam/admin_teacher.html',context=dict)

@login_required(login_url='adminlogin')
def admin_view_teacher_view(request):
    teachers= TMODEL.Teacher.objects.all().filter(status=True)
    return render(request,'exam/admin_view_teacher.html',{'teachers':teachers})


@login_required(login_url='adminlogin')
def update_teacher_view(request,pk):
    teacher=TMODEL.Teacher.objects.get(id=pk)
    user=TMODEL.User.objects.get(id=teacher.user_id)
    userForm=TFORM.TeacherUserForm(instance=user)
    teacherForm=TFORM.TeacherForm(request.FILES,instance=teacher)
    mydict={'userForm':userForm,'teacherForm':teacherForm}
    if request.method=='POST':
        userForm=TFORM.TeacherUserForm(request.POST,instance=user)
        teacherForm=TFORM.TeacherForm(request.POST,request.FILES,instance=teacher)
        if userForm.is_valid() and teacherForm.is_valid():
            user=userForm.save()
            user.set_password(user.password)
            user.save()
            teacherForm.save()
            return redirect('admin-view-teacher')
    return render(request,'exam/update_teacher.html',context=mydict)



@login_required(login_url='adminlogin')
def delete_teacher_view(request,pk):
    teacher=TMODEL.Teacher.objects.get(id=pk)
    user=User.objects.get(id=teacher.user_id)
    user.delete()
    teacher.delete()
    return HttpResponseRedirect('/admin-view-teacher')




@login_required(login_url='adminlogin')
def admin_view_pending_teacher_view(request):
    teachers= TMODEL.Teacher.objects.all().filter(status=False)
    return render(request,'exam/admin_view_pending_teacher.html',{'teachers':teachers})


@login_required(login_url='adminlogin')
def approve_teacher_view(request,pk):
    teacherSalary=forms.TeacherSalaryForm()
    if request.method=='POST':
        teacherSalary=forms.TeacherSalaryForm(request.POST)
        if teacherSalary.is_valid():
            teacher=TMODEL.Teacher.objects.get(id=pk)
            teacher.salary=teacherSalary.cleaned_data['salary']
            teacher.status=True
            teacher.save()
        else:
            print("form is invalid")
        return HttpResponseRedirect('/admin-view-pending-teacher')
    return render(request,'exam/salary_form.html',{'teacherSalary':teacherSalary})

@login_required(login_url='adminlogin')
def reject_teacher_view(request,pk):
    teacher=TMODEL.Teacher.objects.get(id=pk)
    user=User.objects.get(id=teacher.user_id)
    user.delete()
    teacher.delete()
    return HttpResponseRedirect('/admin-view-pending-teacher')

@login_required(login_url='adminlogin')
def admin_view_teacher_salary_view(request):
    teachers= TMODEL.Teacher.objects.all().filter(status=True)
    return render(request,'exam/admin_view_teacher_salary.html',{'teachers':teachers})




@login_required(login_url='adminlogin')
def admin_student_view(request):
    dict={
    'total_student':SMODEL.Student.objects.all().count(),
    }
    return render(request,'exam/admin_student.html',context=dict)

@login_required(login_url='adminlogin')
def admin_view_student_view(request):
    students= SMODEL.Student.objects.all()
    return render(request,'exam/admin_view_student.html',{'students':students})



@login_required(login_url='adminlogin')
def update_student_view(request,pk):
    student=SMODEL.Student.objects.get(id=pk)
    user=SMODEL.User.objects.get(id=student.user_id)
    userForm=SFORM.StudentUserForm(instance=user)
    studentForm=SFORM.StudentForm(request.FILES,instance=student)
    mydict={'userForm':userForm,'studentForm':studentForm}
    if request.method=='POST':
        userForm=SFORM.StudentUserForm(request.POST,instance=user)
        studentForm=SFORM.StudentForm(request.POST,request.FILES,instance=student)
        if userForm.is_valid() and studentForm.is_valid():
            user=userForm.save()
            user.set_password(user.password)
            user.save()
            studentForm.save()
            return redirect('admin-view-student')
    return render(request,'exam/update_student.html',context=mydict)



@login_required(login_url='adminlogin')
def delete_student_view(request,pk):
    student=SMODEL.Student.objects.get(id=pk)
    user=User.objects.get(id=student.user_id)
    user.delete()
    student.delete()
    return HttpResponseRedirect('/admin-view-student')


@login_required(login_url='adminlogin')
def admin_course_view(request):
    return render(request,'exam/admin_course.html')


@login_required(login_url='adminlogin')
def admin_add_course_view(request):
    courseForm=forms.CourseForm()
    if request.method=='POST':
        courseForm=forms.CourseForm(request.POST)
        if courseForm.is_valid():        
            courseForm.save()
        else:
            print("form is invalid")
        return HttpResponseRedirect('/admin-view-course')
    return render(request,'exam/admin_add_course.html',{'courseForm':courseForm})


@login_required(login_url='adminlogin')
def admin_view_course_view(request):
    courses = models.Course.objects.all()
    return render(request,'exam/admin_view_course.html',{'courses':courses})

@login_required(login_url='adminlogin')
def delete_course_view(request,pk):
    course=models.Course.objects.get(id=pk)
    course.delete()
    return HttpResponseRedirect('/admin-view-course')



@login_required(login_url='adminlogin')
def admin_question_view(request):
    return render(request,'exam/admin_question.html')


@login_required(login_url='adminlogin')
def admin_add_question_view(request):
    questionForm=forms.QuestionForm()
    if request.method=='POST':
        questionForm=forms.QuestionForm(request.POST)
        if questionForm.is_valid():
            question=questionForm.save(commit=False)
            course=models.Course.objects.get(id=request.POST.get('courseID'))
            question.course=course
            question.save()       
        else:
            print("form is invalid")
        return HttpResponseRedirect('/admin-view-question')
    return render(request,'exam/admin_add_question.html',{'questionForm':questionForm})


@login_required(login_url='adminlogin')
def admin_view_question_view(request):
    courses= models.Course.objects.all()
    return render(request,'exam/admin_view_question.html',{'courses':courses})

@login_required(login_url='adminlogin')
def view_question_view(request,pk):
    questions=models.Question.objects.all().filter(course_id=pk)
    return render(request,'exam/view_question.html',{'questions':questions})

@login_required(login_url='adminlogin')
def delete_question_view(request,pk):
    question=models.Question.objects.get(id=pk)
    question.delete()
    return HttpResponseRedirect('/admin-view-question')

@login_required(login_url='adminlogin')
def admin_view_student_marks_view(request):
    students= SMODEL.Student.objects.all()
    return render(request,'exam/admin_view_student_marks.html',{'students':students})

@login_required(login_url='adminlogin')
def admin_view_marks_view(request,pk):
    courses = models.Course.objects.all()
    response =  render(request,'exam/admin_view_marks.html',{'courses':courses})
    response.set_cookie('student_id',str(pk))
    return response

@login_required(login_url='adminlogin')
def admin_check_marks_view(request,pk):
    course = models.Course.objects.get(id=pk)
    student_id = request.COOKIES.get('student_id')
    student= SMODEL.Student.objects.get(id=student_id)

    results= models.Result.objects.all().filter(exam=course).filter(student=student)
    return render(request,'exam/admin_check_marks.html',{'results':results})
    




def aboutus_view(request):

mock/templates/exam/admin_add_question.html
{% extends "base/dashboard.html" %}
{% load widget_tweaks %}
{% load static %}

{% block sidebar %} 
  {% include "base/components/admin-sidebar.html" %} 
{% endblock %} 

{% block main %}
<div class="dashboard-form">
  <h3 style="margin-bottom: 2.5rem">Ajouter un examen</h3>
  <form method="POST" autocomplete="off">
    {%csrf_token%}
    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      <label for="question" class="input-select-label">Examens</label>
      {% render_field questionForm.courseID|attr:'required:true' %}
    </div>

    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      <label for="question" class="input-select-label">Question</label>
      {% render_field questionForm.question|attr:'required:true' placeholder="Example: Laquelle des options suivantes n est pas une phase du modèle de prototypage?" %}
    </div>

    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      {% render_field questionForm.marks|attr:'required:true' placeholder="" %}
      <label for="question_number" class="input-label">Note</label>
    </div>

    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      {% render_field questionForm.option1|attr:'required:true' placeholder="" %}
      <label for="option1" class="input-label">Option 1</label>
    </div>

    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      {% render_field questionForm.option2|attr:'required:true' placeholder="" %}
      <label for="option2" class="input-label">Option 2</label>
    </div>

    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      {% render_field questionForm.option3|attr:'required:true' placeholder="" %}
      <label for="option3" class="input-label">Option 3</label>
    </div>
    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      {% render_field questionForm.option4|attr:'required:true' placeholder="" %}
      <label for="option4" class="input-label">Option 4</label>
    </div>
    <div class="input-wrapper" style="margin-bottom: 1.5rem">
      <label for="answer" class="input-select-label">Réponse correcte</label>
      {% render_field questionForm.answer|attr:'required:true' %}
    </div>

    <button type="submit" class="btn btn-main">Ajouter Examen</button>
  </form>
</div>
{% endblock %}

mock/templates/exam/admin_course.html
{% extends "base/dashboard.html" %}
{% load widget_tweaks %}

{% block sidebar %}
  {% include "base/components/admin-sidebar.html" %}
{% endblock %}

{% block main %}
    <div class="dashboard-link-grid">
      <a href="admin-add-course" class="dashboard-link-card blue">
        <div>
          <h3 style="margin: 0">Ajouter un examen</h3>
        </div>
        <i class="fas fa-plus f-left"></i>
      </a>
      <a href="admin-view-course" class="dashboard-link-card green">
        <div>
          <h3 style="margin: 0">Consulter les examens</h3>
        </div>
        <i class="fas fa-eye f-left"></i>
      </a>
    <div>
{% endblock main %}

mock/templates/exam/admin_dashboard.html
{% extends "base/dashboard.html" %}
{% load widget_tweaks %}

{% block sidebar %}
  {% include "base/components/admin-sidebar.html" %}
{% endblock %}

{% block main %}
    <div class="dashboard-link-grid">
      <a href="admin-view-student" class="dashboard-link-card blue">
        <div>
          <h3>Étudiants inscrits</h3>
          <p>{{total_student}}</p>
        </div>
        <i class="fas fa-user-graduate f-left"></i>
      </a>
      <a href="admin-view-teacher" class="dashboard-link-card green">
        <div>
          <h3>Nombre d'enseignants</h3>
          <p>{{total_teacher}}</p>
        </div>
        <i class="fas fa-chalkboard-teacher f-left"></i>
      </a>
      <a href="admin-view-course" class="dashboard-link-card purple">
        <div>
          <h3>Examens disponibles</h3>
          <p>{{total_course}}</p>
        </div> 
        <i class="fas fa-book f-left"></i>
      </a>
      <a href="admin-view-question" class="dashboard-link-card red">
        <div>
          <h3>Nombre total de questions</h3>
          <p>{{total_question}}</p>
        </div>
        <i class="fas fa-question-circle f-left"></i>
      </a>
    <div>
{% endblock main %}

mock/templates/exam/admin_student.html
{% extends "base/dashboard.html" %}
{% load widget_tweaks %}

{% block sidebar %}
  {% include "base/components/admin-sidebar.html" %}
{% endblock %}

{% block main %}
    <div class="dashboard-link-grid">
      <a href="admin-view-student" class="dashboard-link-card blue">
        <div>
          <h3>Nombre d'étudiants inscrits</h3>
          <p>{{total_student}}</p>
        </div>
        <i class="fas fa-user-graduate f-left"></i>
      </a>
      <a href="admin-view-student-marks" class="dashboard-link-card green">
        <div>
          <h3 style="margin: 0">Résultats des étudiants</h3>
        </div>
        <i class="fas fa-sort-numeric-up f-left"></i>
      </a>
    <div>
{% endblock main %}

mock/templates/exam/admin_teacher.html
{% extends "base/dashboard.html" %}
{% load widget_tweaks %}

{% block sidebar %}
  {% include "base/components/admin-sidebar.html" %}
{% endblock %}

{% block main %}
    <div class="dashboard-link-grid">
      <a href="admin-view-teacher" class="dashboard-link-card blue">
        <div>
          <h3>Nombre d'enseignants approuvés</h3>
          <p>{{total_teacher}}</p>
        </div>
        <i class="fas fa-chalkboard-teacher f-left"></i>
      </a>
      <a href="admin-view-pending-teacher" class="dashboard-link-card green">
        <div>
          <h3>Nombre d'enseignants en attente</h3>
          <p>{{pending_teacher}}</p>
        </div>
        <i class="fas fa-sync-alt f-left"></i>
      </a>
      <a href="admin-view-teacher-salary" class="dashboard-link-card red">
        <div>
          <h3>Salaire total des enseignants</h3>
          <p>{{salary}}</p>
        </div>
        <i class="fas fa-dollar-sign f-left"></i>
      </a>
    <div>
{% endblock main %}

mock/templates/exam/admin_view_marks.html
{% extends 'exam/adminbase.html' %}
{% block content %}
{%load static%}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Exams</h6>
    </div>
    <table class="table table-hover table-bordered" id="dev-table">
      <thead>
        <tr>

          <th>Exam Name</th>
          
          <th>Action</th>
        </tr>
      </thead>
      {% for t in courses %}
      <tr>

        <td> {{t.course_name}}</td>
        
        
        <td><a class="btn btn-danger btn-sm" style="border-radius: 0%;" href="{% url 'admin-check-marks' t.id  %}"><span class="glyphicon glyphicon-eye-open"></span> View Marks</a></td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

mock/templates/exam/admin_view_student_marks.html
{% extends "base/dashboard.html" %} 
{% load static %}

{% block sidebar %} 
{% include "base/components/admin-sidebar.html" %}
{% endblock %} 

{% block main %}
<div class="dashboard-exams">
  <h3>Mes résultats</h3>
  <div class="dashboard-exams-table">
    <div class="dashboard-exams-table-header">
      <div>Nom</div>
      <div>Photo</div>
      <div>Action</div>
    </div>
    <div class="dashboard-exams-table-body">
      {% for t in students %}
      <div class="dashboard-exams-table-row">
        <div>{{t.get_name}}</div>
        <div>
          <img src="{% static t.profile_pic.url %}" alt="Profile Pic" height="40px" width="40px" />
        </div>
        <div>
          <a class="dashboard-exams-table-row-action" href="{% url 'admin-view-marks' t.id  %}">
            <i class="fas fa-eye"></i>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock main %}

mock/templates/exam/admin_view_teacher.html
{% extends "base/dashboard.html" %} 
{% load static %}

{% block sidebar %} 
{% include "base/components/admin-sidebar.html" %}
{% endblock %} 

{% block main %}
<div class="dashboard-exams">
  <h3>Mes résultats</h3>
  <div class="dashboard-exams-table">
    <div class="dashboard-exams-table-header">
      <div>Nom</div>
      <div>Photo</div>
      <div>Téléphone</div>
      <div>Adresse</div>
      <div>Actions</div>
    </div>
    <div class="dashboard-exams-table-body">
      {% for t in teachers %}
      <div class="dashboard-exams-table-row">
        <div>{{t.get_name}}</div>
        <div>
          <img src="{% static t.profile_pic.url %}" alt="Photo de Profile" height="40px" width="40px" />
        </div>
        <div>{{t.mobile}}</div>
        <div>{{t.address}}</div>
        <div>
          <a class="dashboard-exams-table-row-action" href="{% url 'update-teacher' t.id  %}">
            <i class="fas fa-edit"></i>
          </a>
          <a class="dashboard-exams-table-row-action" href="{% url 'delete-teacher' t.id  %}">
            <i class="fas fa-trash"></i>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock main %}

mock/templates/exam/contactussuccess.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <style media="screen">
    .jumbotron {
      margin-bottom: 0px;
    }

    .jumbotron h1 {
      text-align: center;
    }
  </style>

</head>

<body>

  {% include "exam/navbar.html" %}
  <br><br>
  <div class="jumbotron">
    <h1 class="display-4">Your message sent successfully !</h1>
    <p class="lead">We will respond to your feedback soon</p>
    <hr class="my-4">
    <p>Check other features of website !</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="/" role="button">HOME</a>
    </p>
  </div>

  {% include "exam/footer.html" %}
</body>

</html>

mock/templates/exam/salary_form.html
{% extends "base/dashboard.html" %} 
{% load widget_tweaks %}
{% load static %}

{% block sidebar %} 
{% include "base/components/admin-sidebar.html" %}
{% endblock %} 

{% block main %}
  <div class="dashboard-form">
    <h3>Veuillez saisir le montant du salaire.</h3>
    <form method="POST" autocomplete="off">
      {%csrf_token%}
      <div class="input-wrapper" style="margin-bottom: 1.5rem">
        {% render_field teacherSalary.salary class="input-text" placeholder="" %}
        <label for="id_salary" class="input-label">Salair (par mois)</label>
      </div>
      <button type="submit" class="btn btn-main">Approuver</button>
    </form>
  </div>
{% endblock %}

mock/templates/exam/view_question.html
{% extends "base/dashboard.html" %} 
{% load static %}

{% block sidebar %} 
{% include "base/components/admin-sidebar.html" %}
{% endblock %} 

{% block main %}
<div class="dashboard-exams">
  <h3>Mes résultats</h3>
  <div class="dashboard-exams-table">
    <div class="dashboard-exams-table-header">
      <div>Questions</div>
      <div>Note</div>
      <div>Actions</div>
    </div>
    <div class="dashboard-exams-table-body">
      {% for c in questions %}
      <div class="dashboard-exams-table-row">
        <div>{{c.question}}</div>
        <div>{{c.marks}}</div>
        <div>
          <a class="dashboard-exams-table-row-action" href="{% url 'delete-question' c.id  %}">
            <i class="fas fa-trash"></i>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock main %}